### PR TITLE
Minor changes to in-memory resources implementation

### PR DESCRIPTION
**Pull request by guillaume-be**
Hello @mweber15 ,

Thank you very much for the PR opened at https://github.com/guillaume-be/rust-bert/pull/375. I started reviewing the code and realized the comments were getting lengthy and it is maybe easier to submit a small update PR. This removes as suggested the  `Resource::NamedTensors` for now.

I have added a few changes to make the code lighter to use, and to avoid needing to take ownership of the buffer to create the `BufferResource`, please let me know what you think

### CODE REVIEW

**Comment by mweber15** [comment]
Definitely looks like a big improvement; thanks so much for taking the time to make these changes!

I haven't had the opportunity yet to test this with the code I have that is using my branch, but I hope to get to that within a few days. I'll incorporate this into my PR and update the base branch once I've done that.

What are your thoughts on user code that wants to assume that `ResourceProvider` is `Send + Sync` based on the properties of the existing implementations? Do you foresee adding something like my ill-conceived `TensorResource` that would necessitate leaving the trait open to non-`Send + Sync` implementations?

**Comment by guillaume-be** [comment]
Hi @mweber15 ,

I have no strong feelings about the explicit `Send + Sync` typing, please feel free to add back if you believe this is a significant risk going forward.

**Comment by mweber15** [comment]
Hi @guillaume-be,

Making `BufferResource` non-owning seems to require additional changes to enable the borrow checker to reason about the lifetime. Consider this simple usage:

```diff
--- a/examples/summarization_bart.rs
+++ b/examples/summarization_bart.rs
@@ -29,9 +29,8 @@ fn main() -> anyhow::Result<()> {
     let merges_resource = Box::new(RemoteResource::from_pretrained(
         BartMergesResources::DISTILBART_CNN_6_6,
     ));
-    let model_resource = Box::new(RemoteResource::from_pretrained(
-        BartModelResources::DISTILBART_CNN_6_6,
-    ));
+    let weights = std::fs::read("/tmp/rust_model.ot").unwrap();
+    let model_resource = Box::new(rust_bert::resources::BufferResource { data: &weights });

     let summarization_config = SummarizationConfig {
         model_resource,
```

```
% cargo r --example summarization_bart
   Compiling rust-bert v0.20.1-alpha (/home/matt/src/rust-bert)
error[E0597]: `weights` does not live long enough
  --> examples/summarization_bart.rs:31:80
   |
31 |     let model_resource = Box::new(rust_bert::resources::BufferResource { data: &weights });
   |                                                                                ^^^^^^^^ borrowed value does not live long enough
...
34 |         model_resource,
   |         -------------- cast requires that `weights` is borrowed for `'static`
...
77 | }
   | - `weights` dropped here while still borrowed

For more information about this error, try `rustc --explain E0597`.
error: could not compile `rust-bert` due to previous error
```

Unless I'm mistaken, everywhere that might refer to `BufferResource` via a `Box<dyn ResourceProvider>` now needs an explicit lifetime to enable this. For example:

```rust
pub struct SummarizationConfig<'a> {
    ...
    pub model_resource: Box<dyn ResourceProvider + Send + 'a>,
    ...
}
```

This would in turn require `impl<'a> SummarizationConfig<'a>` and similar additions of lifetimes where they aren't currently needed.

I think it's preferable for the `BufferResource` to own its data. It seems to me that the `LocalResource` stores a `std::path::PathBuf` instead of a `std::path::Path` for similar reasons. My current usage seems to be also be simpler if `BufferResource` is owning, as my code also needs to introduce explicit lifetimes if it is non-owning.

What do you think?

**Comment by mweber15** [comment]
For context, [here](https://github.com/guillaume-be/rust-bert/commit/6ac52eb943304378c6de28e8678175647a3568c8) are the minimal lifetime changes I needed to make to successfully compile the example. I think most of the anonymous lifetimes would need to become named in the event of fully fleshing this out. There may also be other problems -- I haven't thought very carefully about these changes.

I'm not necessarily opposed to going in this direction, and there might be a simpler approach than what this illustrates.

**Comment by guillaume-be** [comment]
Hello @mweber15 ,

That's a good point I did not realize this and would indeed make the implementation cumbersome. The issue with taking ownership is that the config becomes very heavy (it contains all the weights from the model), but worse: after instantiation these get copied over to get loaded as tensors but remain in the config object, meaning you essentially end up with models that are twice as large (1 full copy of the buffer in the config, and 1 full copy as tensors).

I am pushing another proposal that would at least clear up the buffer resource after it has been loaded once, and mark it as invalid to avoid attempting to load from a buffer twice (it gets consumed by `load_weights`).

Please have a look and let me know what you think, or if you find a more elegant way of doing so.

The following now works on my side:
```rust
use rust_bert::bart::BartConfigResources;
use rust_bert::pipelines::common::ModelType;
use rust_bert::pipelines::summarization::{SummarizationConfig, SummarizationModel};
use rust_bert::resources::RemoteResource;

fn main() -> anyhow::Result<()> {
    let config_resource = Box::new(RemoteResource::from_pretrained(
        BartConfigResources::DISTILBART_CNN_6_6,
    ));
    let weights = std::fs::read("tmp/rust_model.ot").unwrap();
    let model_resource = Box::new(rust_bert::resources::BufferResource::from(weights));

    let summarization_config = SummarizationConfig {
        model_type: ModelType::Bart,
        model_resource,
        config_resource,
        ..Default::default()
    };

    let _model = SummarizationModel::new(summarization_config)?;
    Ok(())
}

```

**Comment by guillaume-be** [comment]
Sorry @mweber15 I just read the above. For the same reasons mentioned I believe taking ownership of the buffer is actually the way to go to avoid keeping the buffer twice in memory. Taking a reference will copy the weights to create tensors, and have the requirement to keep the resource buffer lifetime at least equal equal to that of the model and contained config.

**Comment by mweber15** [comment]
Hi @guillaume-be,

Making the `BufferResource` consumable poses a challenge for me. I need to operate on the same resource in different device contexts, which means I'll need to create a new `BufferResource` for each device. Each time I load the data I'll need to have up to three copies of the same model in memory: my original, a `BufferResource` that I copy my data to, and the tensors. After the tensors are created and the `BufferResource` is consumed this will be down to two copies, but never fewer than that. From that perspective, a consumable `BufferResource` actually imposes additional overhead, whereas a reusable `BufferResource` would allow me to discard my original copy after creating the first `BufferResource`, and not need more than two copies resident at once.

It seems like some additional flexibility could be useful here. I'm going to do some more work with my code on top of these changes and see what I can figure out.

**Comment by mweber15** [comment]
Hi @guillaume-be,

After some more thought I think this is equivalent from a user perspective regardless of whether the `BufferResource` is consumed or not. It's not possible to use the same resource with multiple configs. They need to be recreated for each instance of the model. This is pushing me back toward wanting to allow for a non-owning resource -- ideally what I'd like is a way to connect a `Cursor<&[u8]>` that refers to my in-memory model to `VarStore::load_from_stream` without having to make an intermediate copy. I have not successfully implemented that yet, though.

This does fundamentally enable what I need, so I would be happy to go forward with what you have here. I did notice that the `std::mem::replace` does not seem to be doing what is intended: the `data` buffer inside `BufferResource` is still non-empty after `load_weights` returns.

Should I proceed with merging these changes into my PR and then making sure that `load_weights` properly drops the `BufferResource` buffer?

**Comment by guillaume-be** [comment]
hello @mweber15 ,

How about the changes just pushed using shared references and locks. This allows do to something liek this:
```rust
use rust_bert::bart::BartConfigResources;
use rust_bert::pipelines::common::ModelType;
use rust_bert::pipelines::summarization::{SummarizationConfig, SummarizationModel};
use rust_bert::resources::RemoteResource;
use std::sync::{Arc, RwLock};

fn main() -> anyhow::Result<()> {
    let config_resource = Box::new(RemoteResource::from_pretrained(
        BartConfigResources::DISTILBART_CNN_6_6,
    ));
    let weights = std::fs::read("path/to/rust_model.ot").unwrap();
    let rw_lock = RwLock::new(weights);
    let model_resource = Box::new(rust_bert::resources::BufferResource {
        data: Arc::new(rw_lock),
    });

    let summarization_config = SummarizationConfig {
        model_type: ModelType::Bart,
        model_resource,
        config_resource,
        ..Default::default()
    };

    let _model = SummarizationModel::new(summarization_config)?;
    Ok(())
}
```
You should be able to modify the `Vec<u8>` buffer when acquiring the lock, although this will not change the models that loaded the weights before these changes

**Comment by mweber15** [comment]
Hi @guillaume-be,

Yes, this makes a lot of sense to me and allows me to avoid extra copies. I like it a lot! I really appreciate all of the work you have put into this.

Should I merge this and we continue the conversation in my PR, or do you have another preference for proceeding?

**Comment by guillaume-be** [comment]
Yes that sounds good, thank you

**Pull request merged**
